controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_detail_gladiator:
    path:       /gladiator/detail/{id}
    controller: App\Controller\GladiatorController::detail
    methods:    GET|PUT|POST
